# Generated by Django 2.2.7 on 2019-11-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=50)),
                ('make', models.CharField(default='', max_length=50)),
                ('model', models.CharField(default='', max_length=50)),
                ('vin', models.CharField(blank=True, default='', max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=200)),
                ('due_mileage', models.PositiveIntegerField(default='0')),
                ('cycle_mileage', models.PositiveIntegerField(default='0')),
                ('car', models.ForeignKey(default='', on_delete='CASCADE', related_name='maintenances', to='carmaint.Car')),
            ],
        ),
    ]
