# Generated by Django 2.2.7 on 2019-11-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmaint', '0002_auto_20191114_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='cost',
            new_name='labor_cost',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
