# Generated by Django 2.2.7 on 2019-11-15 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmaint', '0004_auto_20191114_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
